/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.final_project_pbo.ui;

import com.mycompany.final_project_pbo.models.DebtTransaction;
import com.mycompany.final_project_pbo.models.LoanStatus;
import com.mycompany.final_project_pbo.models.User;
import com.mycompany.final_project_pbo.repositories.DebtTransactionRepository;
import com.mycompany.final_project_pbo.utils.Response;
import com.mycompany.final_project_pbo.utils.SessionManager;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public final class Hutang extends javax.swing.JPanel {

    /**
     * Creates new form HutangPiutang
     */
    public Hutang() {
        initComponents();
        showAllHutang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        utangTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        IDPeminjaman = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NamaPeminjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AlamatPeminjam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NoTelpPeminjam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TanggalPeminjaman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TanggalPelunasanPeminjaman = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JumlahPeminjaman = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        StatusPeminjaman = new javax.swing.JTextField();
        SimpanPinjaman = new javax.swing.JButton();
        EditPinjaman = new javax.swing.JButton();
        HapusPinjaman = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1742, 1815));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(93, 173, 226));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 173, 226));
        jLabel1.setText("Data Hutang Piutang Pelanggan dan Pegawai");

        utangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nama ", "Status (Pegawai/Pelanggan)", "Alamat Peminjam", "No. Telp Peminjam", "Tanggal Peminjaman", "Tanggal Pelunasan Peminjaman", "Jumlah Peminjaman", "Status Peminjaman"
            }
        ));
        jScrollPane1.setViewportView(utangTable);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("ID Peminjaman:");

        IDPeminjaman.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPeminjamanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Nama Peminjam :");

        NamaPeminjam.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NamaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPeminjamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Status Peminjam :");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Alamat Peminjam :");

        AlamatPeminjam.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        AlamatPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatPeminjamActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("No. Telp Peminjam :");

        NoTelpPeminjam.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NoTelpPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTelpPeminjamActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Tanggal Peminjaman :");

        TanggalPeminjaman.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TanggalPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalPeminjamanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel8.setText("Tanggal Pelunasan Peminjaman : ");

        TanggalPelunasanPeminjaman.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TanggalPelunasanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalPelunasanPeminjamanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setText("Jumlah Peminjaman : ");

        JumlahPeminjaman.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        JumlahPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahPeminjamanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel10.setText("Status Peminjaman : ");

        StatusPeminjaman.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        StatusPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusPeminjamanActionPerformed(evt);
            }
        });

        SimpanPinjaman.setBackground(new java.awt.Color(244, 246, 246));
        SimpanPinjaman.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        SimpanPinjaman.setForeground(new java.awt.Color(93, 173, 226));
        SimpanPinjaman.setText("Simpan Pinjaman");
        SimpanPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPinjamanActionPerformed(evt);
            }
        });

        EditPinjaman.setBackground(new java.awt.Color(244, 246, 246));
        EditPinjaman.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        EditPinjaman.setForeground(new java.awt.Color(93, 173, 226));
        EditPinjaman.setText("Edit Pinjaman");
        EditPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPinjamanActionPerformed(evt);
            }
        });

        HapusPinjaman.setBackground(new java.awt.Color(244, 246, 246));
        HapusPinjaman.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        HapusPinjaman.setForeground(new java.awt.Color(93, 173, 226));
        HapusPinjaman.setText("Hapus Pinjaman");
        HapusPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPinjamanActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(93, 173, 226));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Img/Peminjaman.png"))); // NOI18N
        jLabel11.setText("Menu Peminjaman");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(SimpanPinjaman)
                                .addGap(136, 136, 136)
                                .addComponent(EditPinjaman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(HapusPinjaman))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IDPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(NamaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(AlamatPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(NoTelpPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(TanggalPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(TanggalPelunasanPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(JumlahPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(StatusPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IDPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlamatPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoTelpPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TanggalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TanggalPelunasanPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JumlahPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SimpanPinjaman)
                            .addComponent(EditPinjaman)
                            .addComponent(HapusPinjaman))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void IDPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPeminjamanActionPerformed

    private void NamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPeminjamActionPerformed

    private void AlamatPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatPeminjamActionPerformed

    private void NoTelpPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTelpPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTelpPeminjamActionPerformed

    private void TanggalPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPeminjamanActionPerformed

    private void TanggalPelunasanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalPelunasanPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPelunasanPeminjamanActionPerformed

    private void JumlahPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahPeminjamanActionPerformed

    private void StatusPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusPeminjamanActionPerformed

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    User user = SessionManager.getInstance().getCurrentUser();
    
    private void SimpanPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPinjamanActionPerformed
        try {
            Date jatuhTempo = sdf.parse(TanggalPelunasanPeminjaman.getText());

            DebtTransaction debtTransaction = new DebtTransaction();
            DebtTransactionRepository debtTransactionRepository = new DebtTransactionRepository();

            debtTransaction.setDebtorName("");
            debtTransaction.setAddress("");
            debtTransaction.setPhoneNumber("");
            debtTransaction.setLoanDate("");
            debtTransaction.setDueDate("");
            debtTransaction.setAmount(null);
            debtTransaction.setStatus(LoanStatus.BELUM_LUNAS);
            debtTransaction.setCreatedBy(null);

            Response<DebtTransaction> response = debtTransactionRepository.save(debtTransaction, user.getId());
            if (response.isSuccess()) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
                clearForm();
                showAllHutang();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan: " + response.getMessage());
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal salah! Gunakan format yyyy-MM-dd");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jumlah Peminjaman harus berupa angka.");
        }
    }//GEN-LAST:event_SimpanPinjamanActionPerformed

    private void EditPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPinjamanActionPerformed
        try {
            Date jatuhTempo = sdf.parse(TanggalPelunasanPeminjaman.getText());

            DebtTransaction debtTransaction = new DebtTransaction();
            DebtTransactionRepository debtTransactionRepository = new DebtTransactionRepository();

            debtTransaction.setDebtorName("");
            debtTransaction.setAddress("");
            debtTransaction.setPhoneNumber("");
            debtTransaction.setLoanDate("");
            debtTransaction.setDueDate("");
            debtTransaction.setAmount(null);
            debtTransaction.setStatus(LoanStatus.BELUM_LUNAS);
            debtTransaction.setCreatedBy(null);

            Response<DebtTransaction> response = debtTransactionRepository.update(debtTransaction, user.getId());
            if (response.isSuccess()) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui.");
                clearForm();
                showAllHutang();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui: " + response.getMessage());
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal salah! Gunakan format yyyy-MM-dd");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jumlah/ID Peminjaman harus berupa angka.");
        }
    }//GEN-LAST:event_EditPinjamanActionPerformed

    private void HapusPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPinjamanActionPerformed
        try {
            int id = Integer.parseInt(IDPeminjaman.getText());

            DebtTransactionRepository debtTransactionRepository = new DebtTransactionRepository();

            int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                Response<Boolean> response = debtTransactionRepository.deleteById(id, user.getId());
                if (response.isSuccess()) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    clearForm();
                    showAllHutang();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus: " + response.getMessage());
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID tidak valid.");
        }
    }//GEN-LAST:event_HapusPinjamanActionPerformed

    public void showAllHutang() {
        DebtTransactionRepository debtTransactionRepository = new DebtTransactionRepository();
        Response<ArrayList<DebtTransaction>> allResponse = debtTransactionRepository.findAll(user.getId());

        if (!allResponse.isSuccess() || allResponse.getData() == null) {
            JOptionPane.showMessageDialog(null, "Tidak ada data hutang piutang yang ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] kolom = {"ID", "Nama Pihak", "Alamat", "No Telepon", "Tanggal Peminjaman", "Tanggal Pelunasan", "Jumlah Peminjaman", "Status Peminjaman", "Created By"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (DebtTransaction u : allResponse.getData()) {
            Object[] row = {
                u.getId(),
                u.getDebtorName(),
                u.getAddress(),
                u.getPhoneNumber(),
                u.getLoanDate(),
                u.getDueDate(),
                u.getAmount(),
                u.getStatus(),
                u.getCreatedBy()
            };
            model.addRow(row);
        }

        utangTable.setModel(model);

        // Cegah listener duplikat
        ListSelectionModel selectionModel = utangTable.getSelectionModel();
        selectionModel.removeListSelectionListener(tableSelectionListener);
        selectionModel.addListSelectionListener(tableSelectionListener);
    }

    private final ListSelectionListener tableSelectionListener = new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = utangTable.getSelectedRow();
                if (selectedRow != -1) {
                    IDPeminjaman.setText(utangTable.getValueAt(selectedRow, 0).toString());
                    NamaPeminjam.setText(utangTable.getValueAt(selectedRow, 1).toString());
                    AlamatPeminjam.setText(utangTable.getValueAt(selectedRow, 2).toString());
                    NoTelpPeminjam.setText(utangTable.getValueAt(selectedRow, 3).toString());
                    TanggalPeminjaman.setText(utangTable.getValueAt(selectedRow, 4).toString());
                    TanggalPelunasanPeminjaman.setText(utangTable.getValueAt(selectedRow, 5).toString());
                    JumlahPeminjaman.setText(utangTable.getValueAt(selectedRow, 6).toString());
                    StatusPeminjaman.setText(utangTable.getValueAt(selectedRow, 7).toString());
                } else {
                    resetFormFields();
                }
            }
        }

        private void resetFormFields() {
            IDPeminjaman.setText("");
            NamaPeminjam.setText("");
            AlamatPeminjam.setText("");
            NoTelpPeminjam.setText("");
            TanggalPeminjaman.setText("");
            TanggalPelunasanPeminjaman.setText("");
            JumlahPeminjaman.setText("");
            StatusPeminjaman.setText("");
        }
    };

    private void clearForm() {
        IDPeminjaman.setText("");
        NamaPeminjam.setText("");
        AlamatPeminjam.setText("");
        NoTelpPeminjam.setText("");
        TanggalPeminjaman.setText("");
        TanggalPelunasanPeminjaman.setText("");
        JumlahPeminjaman.setText("");
        StatusPeminjaman.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatPeminjam;
    private javax.swing.JButton EditPinjaman;
    private javax.swing.JButton HapusPinjaman;
    private javax.swing.JTextField IDPeminjaman;
    private javax.swing.JTextField JumlahPeminjaman;
    private javax.swing.JTextField NamaPeminjam;
    private javax.swing.JTextField NoTelpPeminjam;
    private javax.swing.JButton SimpanPinjaman;
    private javax.swing.JTextField StatusPeminjaman;
    private javax.swing.JTextField TanggalPelunasanPeminjaman;
    private javax.swing.JTextField TanggalPeminjaman;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable utangTable;
    // End of variables declaration//GEN-END:variables
}
