/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.final_project_pbo.ui;

import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.final_project_pbo.models.FinancialReport;
import com.mycompany.final_project_pbo.services.FinanceService;

/**
 *
 * @author muham
 */
public class Keuangan extends javax.swing.JPanel {

    /**
     * Creates new form Keuangan
     */
    public Keuangan() {
        initComponents();
        initializeComponents(); // Call the method to initialize components
    }

    private final FinanceService financeService = new FinanceService();

    private void initializeComponents() {
        populateComboBox();
        clearFields();
        ButtonTampilkan.addActionListener(evt -> selectedFinancialReport());
        JenisLaporan.addActionListener(evt -> {
            String selectedReportType = (String) JenisLaporan.getSelectedItem();
            if (selectedReportType != null) {
                switch (selectedReportType) {
                    case "Harian" -> TanggalLaporan.setText(LocalDate.now().toString());
                    case "Mingguan" -> TanggalLaporan.setText("Pilih tanggal awal dan akhir");
                    case "Bulanan" -> TanggalLaporan.setText("Pilih bulan dan tahun");
                    default -> TanggalLaporan.setText("");
                }
            }
        });
    }

    private void selectedFinancialReport() {
        String selectedReportType = (String) JenisLaporan.getSelectedItem();
        if (selectedReportType != null) {
            switch (selectedReportType) {
                case "Harian" -> {
                    var dailyReports = financeService.getDailyFinancialReports();
                    if (dailyReports.isSuccess() && dailyReports.getData() != null) {
                        populateKeuanganTable(dailyReports.getData());

                        TotalPengeluaran.setText(String.valueOf(dailyReports.getData().stream()
                                .mapToDouble(FinancialReport::getTotalExpenses).sum()));
                        TotalPenjualan.setText(String.valueOf(dailyReports.getData().stream()
                                .mapToDouble(FinancialReport::getTotalIncome).sum()));
                        LabaBersih.setText(String.valueOf(dailyReports.getData().stream()
                                .mapToDouble(FinancialReport::getNetProfit).sum()));
                        PriodeLaporan.setText(LocalDate.now().toString());
                    } else if (dailyReports.getData() == null) {
                        showErrorDialog("Tidak ada laporan harian yang tersedia.");
                    } else {
                        showErrorDialog("Gagal mengambil laporan harian: " + dailyReports.getMessage());
                    }
                }
                case "Mingguan" -> {
                    // TODO: Implement weekly report
                }
                case "Bulanan" -> {
                    // TODO: Implement monthly report
                }
                default -> showErrorDialog("Jenis laporan tidak dikenali.");
            }
        }
    }

    private void populateKeuanganTable(ArrayList<FinancialReport> reports) {
        String[] columnNames = { "Tanggal", "Total Transaksi", "Pendapatan", "Pengeluaran", "Laba" };
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        for (FinancialReport report : reports) {
            Object[] row = new Object[] {
                    report.getDate(),
                    report.getTotalTransactions(),
                    report.getTotalIncome(),
                    report.getTotalExpenses(),
                    report.getNetProfit()
            };
            tableModel.addRow(row);
        }
        TabelLaporaKeuangan.setModel(tableModel);
    }

    private void populateComboBox() {
        JenisLaporan.removeAllItems();
        JenisLaporan.addItem("");
        JenisLaporan.addItem("Harian");
        JenisLaporan.addItem("Mingguan");
        JenisLaporan.addItem("Bulanan");
    }

    private void showErrorDialog(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void clearFields() {
        // Clear all input fields
        TanggalLaporan.setText("");
        TotalPenjualan.setText("");
        TotalPengeluaran.setText("");
        LabaBersih.setText("");
        PriodeLaporan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JenisLaporan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TanggalLaporan = new javax.swing.JTextField();
        ButtonTampilkan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TotalPenjualan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TotalPengeluaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LabaBersih = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PriodeLaporan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporaKeuangan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        BulanLaporan = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 173, 226));
        jLabel1.setText("Laporan Keuangan  Toko Berkah Abadi");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Jenis Laporan : ");

        JenisLaporan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        JenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harian", "Mingguan", "Bulanan" }));
        JenisLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisLaporanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Tanggal Laporan :");

        TanggalLaporan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        ButtonTampilkan.setBackground(new java.awt.Color(93, 173, 226));
        ButtonTampilkan.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        ButtonTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTampilkan.setText("Tampilkan");
        ButtonTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTampilkanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Total Penjualan : ");

        TotalPenjualan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TotalPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPenjualanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Total Pengeluaran : ");

        TotalPengeluaran.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TotalPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPengeluaranActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Laba Bersih :");

        LabaBersih.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabaBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabaBersihActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Priode Laporan: ");

        PriodeLaporan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        PriodeLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriodeLaporanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 173, 226));
        jLabel8.setText("Tabel Laporan Keuangan:");

        TabelLaporaKeuangan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Tanggal", "Total Transaksi", "Pendapatan", "Pengeluaran", "Laba"
                }));
        jScrollPane1.setViewportView(TabelLaporaKeuangan);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(93, 173, 226));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Img/Laporan_Keuangan.png"))); // NOI18N
        jLabel9.setText("Menu Laporan Keuangan");

        BulanLaporan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        BulanLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1712, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel4))
                                    .addGap(73, 73, 73)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TotalPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                                .addComponent(PriodeLaporan))
                                            .addComponent(LabaBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(TotalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonTampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TanggalLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(BulanLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JenisLaporan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGap(0, 1, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TanggalLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BulanLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ButtonTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(PriodeLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TotalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LabaBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)))
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void JenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JenisLaporanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_JenisLaporanActionPerformed

    private void ButtonTampilkanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonTampilkanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ButtonTampilkanActionPerformed

    private void TotalPenjualanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalPenjualanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalPenjualanActionPerformed

    private void TotalPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalPengeluaranActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalPengeluaranActionPerformed

    private void LabaBersihActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LabaBersihActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_LabaBersihActionPerformed

    private void PriodeLaporanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PriodeLaporanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PriodeLaporanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BulanLaporan;
    private javax.swing.JButton ButtonTampilkan;
    private javax.swing.JComboBox<String> JenisLaporan;
    private javax.swing.JTextField LabaBersih;
    private javax.swing.JTextField PriodeLaporan;
    private javax.swing.JTable TabelLaporaKeuangan;
    private javax.swing.JTextField TanggalLaporan;
    private javax.swing.JTextField TotalPengeluaran;
    private javax.swing.JTextField TotalPenjualan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
