/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.final_project_pbo.ui;

import com.mycompany.final_project_pbo.models.Category;
import com.mycompany.final_project_pbo.models.LogActivity;
import com.mycompany.final_project_pbo.models.Product;
import com.mycompany.final_project_pbo.models.User;
import com.mycompany.final_project_pbo.repositories.CategoryRepository;
import com.mycompany.final_project_pbo.repositories.LogActivityRepository;
import com.mycompany.final_project_pbo.repositories.ProductRepository;
import com.mycompany.final_project_pbo.repositories.UserRepository;
import com.mycompany.final_project_pbo.utils.Response;
import com.mycompany.final_project_pbo.utils.SessionManager;

import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class ManajemenBarang extends javax.swing.JPanel {

    /**
     * Creates new form ManajemenBarang
     */
    public ManajemenBarang() {
        initComponents();
        showAllProduct();
        showAllRiwayatAktivitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SortItem = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelManajemenBarang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        IDBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        KategoriBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HargaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        StockBarang = new javax.swing.JTextField();
        ButtonTambahBarang = new javax.swing.JButton();
        ButtonEditBarang = new javax.swing.JButton();
        ButtonHapusBarang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SortRiwayatAktivitas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelRiwayatAktivitas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        SearchBarang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 173, 226));
        jLabel1.setText("Data Barang Toko Berkah Abadi");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Urutkan Berdasarkan: ");

        SortItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SortItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDBarang", "Nama", "Kategori", "Harga", "Stock" }));

        TabelManajemenBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDBarang", "Nama", "Kategori", "Harga", "Stock"
            }
        ));
        jScrollPane1.setViewportView(TabelManajemenBarang);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("ID Barang: ");

        IDBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Nama Barang: ");

        NamaBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Kategori Barang: ");

        KategoriBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        KategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriBarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Harga Barang: ");

        HargaBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        HargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Stock Barang: ");

        StockBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        StockBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockBarangActionPerformed(evt);
            }
        });

        ButtonTambahBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ButtonTambahBarang.setForeground(new java.awt.Color(93, 173, 226));
        ButtonTambahBarang.setText("Tambah Barang");
        ButtonTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahBarangActionPerformed(evt);
            }
        });

        ButtonEditBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ButtonEditBarang.setForeground(new java.awt.Color(93, 173, 226));
        ButtonEditBarang.setText("Edit Barang");
        ButtonEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditBarangActionPerformed(evt);
            }
        });

        ButtonHapusBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ButtonHapusBarang.setForeground(new java.awt.Color(93, 173, 226));
        ButtonHapusBarang.setText("Hapus Barang");
        ButtonHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusBarangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 173, 226));
        jLabel8.setText("Riwayat Aktivitas");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Urutkan Berdasarkan: ");

        SortRiwayatAktivitas.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SortRiwayatAktivitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal&Waktu", "Nama", "Tambah/Edit/Hapus", "Jumlah" }));
        SortRiwayatAktivitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortRiwayatAktivitasActionPerformed(evt);
            }
        });

        TabelRiwayatAktivitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal&Waktu", "Nama", "Tambah/Hapus/Edit", "Jumlah"
            }
        ));
        jScrollPane2.setViewportView(TabelRiwayatAktivitas);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(93, 173, 226));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laporan_Keuangan.png"))); // NOI18N
        jLabel10.setText("Menu Barang");

        SearchBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SearchBarang.setText("Search Barang");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(114, 114, 114)
                                .addComponent(SortItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1507, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(SearchBarang)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(205, 205, 205)
                                .addComponent(SortRiwayatAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(ButtonTambahBarang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonEditBarang)
                                    .addGap(80, 80, 80)
                                    .addComponent(ButtonHapusBarang))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(195, 195, 195)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NamaBarang)
                                        .addComponent(IDBarang)
                                        .addComponent(KategoriBarang)
                                        .addComponent(HargaBarang)
                                        .addComponent(StockBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SortItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StockBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonTambahBarang)
                            .addComponent(ButtonEditBarang)
                            .addComponent(ButtonHapusBarang))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(SortRiwayatAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBarangActionPerformed

    private void KategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriBarangActionPerformed

    private void HargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaBarangActionPerformed

    private void StockBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockBarangActionPerformed

    private void SortRiwayatAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortRiwayatAktivitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SortRiwayatAktivitasActionPerformed

    User currentUser = SessionManager.getInstance().getCurrentUser();

    private void ButtonEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditBarangActionPerformed
        try {
            Product product = new Product();
            ProductRepository productRepository = new ProductRepository();

            product.setId(null);
            product.setName("");
            product.setBarcode("");
            product.setCategoryId(null);
            product.setPrice(null);
            product.setStock(null);

            Response<Product> response = productRepository.update(product, currentUser.getId());

            if (response.isSuccess()) {
                JOptionPane.showMessageDialog(this, "Produk berhasil diperbarui.");
                clearForm();
                showAllProduct();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui produk: " + response.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka valid.",
                    "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonEditBarangActionPerformed

    private void ButtonTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahBarangActionPerformed
        try {
            Product product = new Product();
            ProductRepository productRepository = new ProductRepository();

            product.setName("");
            product.setBarcode("");
            product.setCategoryId(null);
            product.setPrice(null);
            product.setStock(null);

            Response<Product> response = productRepository.save(product, currentUser.getId());

            if (response.isSuccess()) {
                JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan.");
                clearForm();
                showAllProduct();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan produk: " + response.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka valid.",
                    "Input Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_ButtonTambahBarangActionPerformed

    private void ButtonHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusBarangActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus produk ini?", 
                        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(IDBarang.getText());

                ProductRepository productRepository = new ProductRepository();

                Response<Boolean> response = productRepository.deleteById(id, currentUser.getId());
                if (response.isSuccess()) {
                    JOptionPane.showMessageDialog(this, "Produk berhasil dihapus.");
                    clearForm();
                    showAllProduct();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus produk: " + response.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID tidak valid.",
                        "Input Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButtonHapusBarangActionPerformed

    private void showAllProduct() {
        ProductRepository productRepository = new ProductRepository();
        CategoryRepository categoryRepository = new CategoryRepository();
        Response<ArrayList<Product>> allResponse = productRepository.findAll(currentUser.getId());

        String[] kolom = {"Id", "Nama Barang", "Barcode", "Kategori", "Harga", "Stock"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (allResponse.isSuccess()) {
            // Cache kategori untuk menghindari query berulang
            HashMap<Integer, String> categoryCache = new HashMap<>();

            for (Product p : allResponse.getData()) {
                String categoryName;

                if (categoryCache.containsKey(p.getCategoryId())) {
                    categoryName = categoryCache.get(p.getCategoryId());
                } else {
                    Response<Category> categoryResponse = categoryRepository.findById(p.getCategoryId(), currentUser.getId());
                    categoryName = categoryResponse.isSuccess() && categoryResponse.getData() != null
                            ? categoryResponse.getData().getName()
                            : "Kategori Tidak Dikenal";
                    categoryCache.put(p.getCategoryId(), categoryName);
                }

                Object[] row = {
                    p.getId(),
                    p.getName(),
                    p.getBarcode(),
                    categoryName,
                    p.getPrice(),
                    p.getStock()
                };
                model.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Gagal memuat data produk: " + allResponse.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        TabelManajemenBarang.setModel(model);

        // Hindari duplikasi listener
        ListSelectionModel selectionModel = TabelManajemenBarang.getSelectionModel();
        selectionModel.removeListSelectionListener(tableSelectionListener);
        selectionModel.addListSelectionListener(tableSelectionListener);
    }

    private final ListSelectionListener tableSelectionListener = new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = TabelManajemenBarang.getSelectedRow();
                if (selectedRow != -1) {
                    IDBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 0).toString());
                    NamaBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 1).toString());
                    // BarcodeBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 2).toString());
                    KategoriBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 3).toString());
                    HargaBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 4).toString());
                    StockBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 5).toString());
                } else {
                    resetProductFormFields();
                }
            }
        }

        private void resetProductFormFields() {
            IDBarang.setText("");
            NamaBarang.setText("");
            // BarcodeBarang.setText("");
            KategoriBarang.setText("");
            HargaBarang.setText("");
            StockBarang.setText("");
        }
    };
    
    private void clearForm() {
        IDBarang.setText("");
        NamaBarang.setText("");
        // BarcodeBarang.setText("");
        KategoriBarang.setText("");
        HargaBarang.setText("");
        StockBarang.setText("");
    }

    private void showAllRiwayatAktivitas() {
        LogActivityRepository logActivityRepository = new LogActivityRepository();
        Response<ArrayList<LogActivity>> allResponse = logActivityRepository.findAll();

        UserRepository userRepository = new UserRepository();

        String[] kolom = {"Tanggal & Waktu", "Nama", "Tambah/Hapus/Edit"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (allResponse.isSuccess()) {
            for (LogActivity log : allResponse.getData()) {
                // === FILTER BERDASARKAN MODULE ===
                if (!"ProductRepository".equalsIgnoreCase(log.getModule())) {
                    continue; // skip jika bukan dari ProductRepository
                }

                Response<User> userResponse = userRepository.findById(log.getUserId(), currentUser.getId());

                Object[] row = {
                    log.getCreatedAt(),
                    userResponse.isSuccess() && userResponse.getData() != null
                        ? userResponse.getData().getUsername()
                        : "Unknown",
                    log.getAction()
                };
                model.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Gagal memuat riwayat aktivitas: " + allResponse.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        TabelRiwayatAktivitas.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditBarang;
    private javax.swing.JButton ButtonHapusBarang;
    private javax.swing.JButton ButtonTambahBarang;
    private javax.swing.JTextField HargaBarang;
    private javax.swing.JTextField IDBarang;
    private javax.swing.JTextField KategoriBarang;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JTextField SearchBarang;
    private javax.swing.JComboBox<String> SortItem;
    private javax.swing.JComboBox<String> SortRiwayatAktivitas;
    private javax.swing.JTextField StockBarang;
    private javax.swing.JTable TabelManajemenBarang;
    private javax.swing.JTable TabelRiwayatAktivitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
