/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.final_project_pbo.ui;

import com.mycompany.final_project_pbo.models.Category;
import com.mycompany.final_project_pbo.models.LogActivity;
import com.mycompany.final_project_pbo.models.Product;
import com.mycompany.final_project_pbo.models.User;
import com.mycompany.final_project_pbo.repositories.CategoryRepository;
import com.mycompany.final_project_pbo.repositories.LogActivityRepository;
import com.mycompany.final_project_pbo.repositories.ProductRepository;
import com.mycompany.final_project_pbo.repositories.UserRepository;
import com.mycompany.final_project_pbo.utils.Response;
import com.mycompany.final_project_pbo.utils.SessionManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.Comparator;
import java.util.HashMap;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.KeyAdapter;

/**
 *
 * @author muham
 */
public class ManajemenBarang extends javax.swing.JPanel {

        /**
         * Creates new form ManajemenBarang
         */
        public ManajemenBarang() {
                initComponents();
                initializeComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                SortItem = new javax.swing.JComboBox<>();
                jScrollPane1 = new javax.swing.JScrollPane();
                TabelManajemenBarang = new javax.swing.JTable();
                jLabel3 = new javax.swing.JLabel();
                IDBarang = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                NamaBarang = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                HargaBeliBarang = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                StockBarang = new javax.swing.JTextField();
                ButtonTambahBarang = new javax.swing.JButton();
                ButtonEditBarang = new javax.swing.JButton();
                ButtonHapusBarang = new javax.swing.JButton();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                SortRiwayatAktivitas = new javax.swing.JComboBox<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                TabelRiwayatAktivitas = new javax.swing.JTable();
                jLabel10 = new javax.swing.JLabel();
                SearchBarang = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                KategoriBarang = new javax.swing.JComboBox<>();
                clearForm = new javax.swing.JButton();
                jLabel11 = new javax.swing.JLabel();
                HargaJualBarang = new javax.swing.JTextField();
                ButtonScanBarang = new javax.swing.JButton();

                setLayout(new java.awt.CardLayout());

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(93, 173, 226));
                jLabel1.setText("Data Barang Toko Berkah Abadi");

                jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel2.setText("Urutkan Berdasarkan: ");

                SortItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

                TabelManajemenBarang.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "IDBarang", "Nama", "Kategori", "Harga", "Stock"
                                }));
                jScrollPane1.setViewportView(TabelManajemenBarang);

                jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel3.setText("ID Barang: ");

                IDBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                IDBarang.setEnabled(false);

                jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel4.setText("Nama Barang: ");

                NamaBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                NamaBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NamaBarangActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel5.setText("Kategori Barang: ");

                jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel6.setText("Harga Beli Barang: ");

                HargaBeliBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                HargaBeliBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HargaBeliBarangActionPerformed(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel7.setText("Stock Barang: ");

                StockBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                StockBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                StockBarangActionPerformed(evt);
                        }
                });

                ButtonTambahBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                ButtonTambahBarang.setForeground(new java.awt.Color(93, 173, 226));
                ButtonTambahBarang.setText("Tambah Barang");
                ButtonTambahBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ButtonTambahBarangActionPerformed(evt);
                        }
                });

                ButtonEditBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                ButtonEditBarang.setForeground(new java.awt.Color(93, 173, 226));
                ButtonEditBarang.setText("Edit Barang");
                ButtonEditBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ButtonEditBarangActionPerformed(evt);
                        }
                });

                ButtonHapusBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                ButtonHapusBarang.setForeground(new java.awt.Color(93, 173, 226));
                ButtonHapusBarang.setText("Hapus Barang");
                ButtonHapusBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ButtonHapusBarangActionPerformed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(93, 173, 226));
                jLabel8.setText("Riwayat Aktivitas");

                jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                jLabel9.setText("Urutkan Berdasarkan: ");

                SortRiwayatAktivitas.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                SortRiwayatAktivitas.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Tanggal&Waktu", "Nama", "Tambah/Edit/Hapus", "Jumlah" }));
                SortRiwayatAktivitas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SortRiwayatAktivitasActionPerformed(evt);
                        }
                });

                TabelRiwayatAktivitas.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Tanggal&Waktu", "Nama", "Tambah/Hapus/Edit", "Jumlah"
                                }));
                jScrollPane2.setViewportView(TabelRiwayatAktivitas);

                jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(93, 173, 226));
                jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laporan_Keuangan.png"))); // NOI18N
                jLabel10.setText("Menu Barang");

                SearchBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 497, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 290, Short.MAX_VALUE));

                KategoriBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

                clearForm.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                clearForm.setForeground(new java.awt.Color(93, 173, 226));
                clearForm.setText("Bersihkan Kolom");
                clearForm.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                clearFormMouseClicked(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
                jLabel11.setText("Harga Jual Barang:");

                HargaJualBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                HargaJualBarang.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HargaJualBarangActionPerformed(evt);
                        }
                });

                ButtonScanBarang.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
                ButtonScanBarang.setText("Scan Barang");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jScrollPane1)
                                                                                .addComponent(jScrollPane2)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                1507,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addGap(159, 159,
                                                                                                                                                159)
                                                                                                                                .addComponent(SortItem,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                200,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(ButtonScanBarang,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                160,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(42, 42, 42)))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel10,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                200,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(SearchBarang)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel8)
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                jPanel1Layout
                                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                jLabel9)
                                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                SortRiwayatAktivitas,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                210,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                jLabel3)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                jLabel5)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                jLabel6))
                                                                                                                                                                                                .addGap(175, 175,
                                                                                                                                                                                                                175)
                                                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                                                false)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                HargaBeliBarang)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                IDBarang,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                207,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                KategoriBarang,
                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                ButtonTambahBarang)
                                                                                                                                                                                                .addGap(10, 10, 10)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                ButtonEditBarang)
                                                                                                                                                                                                .addGap(10, 10, 10)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                ButtonHapusBarang)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                clearForm)))
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                                                .addComponent(jLabel7))))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGap(264, 264,
                                                                                                                                                                                264)
                                                                                                                                                                .addComponent(NamaBarang,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                207,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(StockBarang,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                207,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                .addComponent(HargaJualBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                207,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jPanel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jLabel10))
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(SortItem,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(15, 15, 15))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(ButtonScanBarang,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                26,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(SearchBarang,
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                275,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(IDBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(NamaBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(15, 15, 15)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(HargaJualBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel11)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(KategoriBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(15, 15, 15)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(HargaBeliBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(StockBarang,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(25, 25, 25)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(ButtonTambahBarang)
                                                                                                                .addComponent(ButtonEditBarang)
                                                                                                                .addComponent(ButtonHapusBarang)
                                                                                                                .addComponent(clearForm))
                                                                                                .addGap(25, 25, 25)
                                                                                                .addComponent(jLabel8)
                                                                                                .addGap(25, 25, 25)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel9)
                                                                                                                .addComponent(SortRiwayatAktivitas,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                265,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                add(jPanel1, "card2");
        }// </editor-fold>//GEN-END:initComponents

        private void clearFormMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clearFormMouseClicked
                // clearForm();
        }// GEN-LAST:event_clearFormMouseClicked

        private void HargaJualBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HargaJualBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_HargaJualBarangActionPerformed

        private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NamaBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_NamaBarangActionPerformed

        private void HargaBeliBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HargaBeliBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_HargaBeliBarangActionPerformed

        private void KategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_KategoriBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_KategoriBarangActionPerformed

        private void HargaBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HargaBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_HargaBarangActionPerformed

        private void StockBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_StockBarangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_StockBarangActionPerformed

        private void SortRiwayatAktivitasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SortRiwayatAktivitasActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_SortRiwayatAktivitasActionPerformed

        User currentUser = SessionManager.getInstance().getCurrentUser();
        Product product = new Product();
        UserRepository userRepository = new UserRepository();
        ProductRepository productRepository = new ProductRepository();
        CategoryRepository categoryRepository = new CategoryRepository();
        LogActivityRepository logActivityRepository = new LogActivityRepository();

        private void ButtonEditBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonEditBarangActionPerformed
                try {
                        Response<ArrayList<Category>> categoryResponse = categoryRepository
                                        .findByName(KategoriBarang.getSelectedItem().toString(), currentUser.getId());
                        if (!categoryResponse.isSuccess() || categoryResponse.getData().isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan.",
                                                "Error", JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        product.setId(Integer.parseInt(IDBarang.getText()));
                        product.setName(NamaBarang.getText());
                        // product.setBarcode(BarcodeBarang.getText());
                        product.setCategoryId(categoryResponse.getData().get(0).getId());
                        product.setPurchasePrice(Double.parseDouble(HargaBeliBarang.getText()));
                        product.setSellingPrice(Double.parseDouble(HargaJualBarang.getText()));
                        product.setStock(Integer.parseInt(StockBarang.getText()));

                        Response<Product> response = productRepository.update(product, currentUser.getId());

                        if (response.isSuccess()) {
                                JOptionPane.showMessageDialog(this, "Produk berhasil diperbarui.");
                                clearForm();
                                populateTableProducts(filteredAndSortedProducts(null));
                        } else {
                                JOptionPane.showMessageDialog(this,
                                                "Gagal memperbarui produk: " + response.getMessage(),
                                                "Error", JOptionPane.ERROR_MESSAGE);
                        }
                } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka valid.",
                                        "Input Error", JOptionPane.WARNING_MESSAGE);
                }
        }// GEN-LAST:event_ButtonEditBarangActionPerformed

        private void ButtonTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonTambahBarangActionPerformed
                try {
                        Response<ArrayList<Category>> categoryResponse = categoryRepository
                                        .findByName(KategoriBarang.getSelectedItem().toString(), currentUser.getId());
                        if (!categoryResponse.isSuccess() || categoryResponse.getData().isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan.",
                                                "Error", JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        product.setName(NamaBarang.getText());
                        // product.setBarcode(BarcodeBarang.getText());
                        product.setCategoryId(categoryResponse.getData().get(0).getId());
                        product.setPurchasePrice(Double.parseDouble(HargaBeliBarang.getText()));
                        product.setSellingPrice(Double.parseDouble(HargaJualBarang.getText()));
                        product.setStock(Integer.parseInt(StockBarang.getText()));

                        Response<Product> response = productRepository.save(product, currentUser.getId());

                        if (response.isSuccess()) {
                                JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan.");
                                clearForm();
                                populateTableProducts(filteredAndSortedProducts(null));
                        } else {
                                JOptionPane.showMessageDialog(this,
                                                "Gagal menambahkan produk: " + response.getMessage(),
                                                "Error", JOptionPane.ERROR_MESSAGE);
                        }
                } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka valid.",
                                        "Input Error", JOptionPane.WARNING_MESSAGE);
                }

        }// GEN-LAST:event_ButtonTambahBarangActionPerformed

        private void ButtonHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonHapusBarangActionPerformed
                int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus produk ini?",
                                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                int id = Integer.parseInt(IDBarang.getText());

                                ProductRepository productRepository = new ProductRepository();

                                Response<Boolean> response = productRepository.deleteById(id, currentUser.getId());
                                if (response.isSuccess()) {
                                        JOptionPane.showMessageDialog(this, "Produk berhasil dihapus.");
                                        clearForm();
                                        populateTableProducts(filteredAndSortedProducts(null));
                                } else {
                                        JOptionPane.showMessageDialog(this,
                                                        "Gagal menghapus produk: " + response.getMessage(),
                                                        "Error", JOptionPane.ERROR_MESSAGE);
                                }
                        } catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(this, "ID tidak valid.",
                                                "Input Error", JOptionPane.WARNING_MESSAGE);
                        }
                }
        }// GEN-LAST:event_ButtonHapusBarangActionPerformed

        private final Map<Integer, String> categoryMap = new HashMap<>();
        private final Map<Integer, String> userMap = new HashMap<>();

        private void initializeComponents() {
                initializeProductTable();
                initializeLogActivityTable();
                populateCategoryComboBox();
                populateSortOptions();

                clearForm.addActionListener(e -> clearForm());

                SearchBarang.addKeyListener(new KeyAdapter() {
                        @Override
                        public void keyReleased(KeyEvent e) {
                                String searchTerm = SearchBarang.getText();
                                List<Product> products = filteredAndSortedProducts(searchTerm);
                                populateTableProducts(products);
                        }
                });

                SortItem.addActionListener(e -> {
                        String searchTerm = SearchBarang.getText();
                        List<Product> products = filteredAndSortedProducts(searchTerm);
                        populateTableProducts(products);
                });
        }

        private void populateCategoryComboBox() {
                try {
                        Response<ArrayList<Category>> response = categoryRepository.findAll(currentUser.getId());
                        if (response.isSuccess()) {
                                for (Category category : response.getData()) {
                                        KategoriBarang.addItem(category.getName());
                                }
                        } else {
                                showError("Gagal memuat kategori: " + response.getMessage());
                        }
                } catch (Exception e) {
                        showError("Terjadi kesalahan saat memuat kategori.");
                }
        }

        private void populateSortOptions() {
                SortItem.removeAllItems();
                SortItem.addItem("");
                SortItem.addItem("Nama");
                SortItem.addItem("Kategori");
                SortItem.addItem("Harga Beli");
                SortItem.addItem("Harga Jual");
                SortItem.addItem("Stok");

                SortRiwayatAktivitas.removeAllItems();
                SortRiwayatAktivitas.addItem("");
                SortRiwayatAktivitas.addItem("Tanggal");
                SortRiwayatAktivitas.addItem("Pengguna");
                SortRiwayatAktivitas.addItem("Log Level");
        }

        private void initializeProductTable() {
                String searchTerm = SearchBarang.getText();
                List<Product> products = filteredAndSortedProducts(searchTerm);
                populateTableProducts(products);
        }

        private void initializeLogActivityTable() {
                List<LogActivity> logActivities = filteredLogActivities();
                populateTableRiwayatAktivitas(logActivities);
        }

        private List<Product> filteredAndSortedProducts(String searchTerm) {
                try {
                        Response<ArrayList<Product>> response = (searchTerm == null || searchTerm.trim().isEmpty())
                                        ? productRepository.findAll(currentUser.getId())
                                        : productRepository.searchByName(searchTerm, currentUser.getId());

                        if (!response.isSuccess()) {
                                showError("Gagal memuat produk: " + response.getMessage());
                                return Collections.emptyList();
                        }

                        List<Product> products = response.getData();

                        // Sorting logic
                        String sortOption = (String) SortItem.getSelectedItem();
                        if (sortOption != null) {
                                switch (sortOption) {
                                        case "Nama":
                                                products.sort(Comparator.comparing(Product::getName));
                                                break;
                                        case "Kategori":
                                                products.sort(Comparator.comparing(Product::getCategoryId));
                                                break;
                                        case "Harga Beli":
                                                products.sort(Comparator.comparing(Product::getPurchasePrice));
                                                break;
                                        case "Harga Jual":
                                                products.sort(Comparator.comparing(Product::getSellingPrice));
                                                break;
                                        case "Stok":
                                                products.sort(Comparator.comparing(Product::getStock));
                                                break;
                                }
                        }

                        // Update categoryMap
                        Response<ArrayList<Category>> categoryResponse = categoryRepository
                                        .findAll(currentUser.getId());
                        if (categoryResponse.isSuccess()) {
                                categoryMap.clear();
                                for (Category category : categoryResponse.getData()) {
                                        categoryMap.put(category.getId(), category.getName());
                                }
                        } else {
                                showError("Gagal memuat kategori: " + categoryResponse.getMessage());
                        }

                        return products;
                } catch (Exception e) {
                        showError("Terjadi kesalahan saat memuat produk.");
                        return Collections.emptyList();
                }
        }

        private List<LogActivity> filteredLogActivities() {
                try {
                        Response<ArrayList<LogActivity>> response = logActivityRepository.findAll();
                        if (!response.isSuccess()) {
                                showError("Gagal memuat riwayat aktivitas: " + response.getMessage());
                                return Collections.emptyList();
                        }

                        List<LogActivity> logActivities = response.getData();

                        // Sorting logic
                        String sortOption = (String) SortRiwayatAktivitas.getSelectedItem();
                        if (sortOption != null && !sortOption.isEmpty()) {
                                switch (sortOption) {
                                        case "Tanggal":
                                                logActivities.sort(Comparator.comparing(LogActivity::getCreatedAt));
                                                break;
                                        case "Pengguna":
                                                logActivities.sort(Comparator.comparing(LogActivity::getUserId)
                                                                .thenComparing(LogActivity::getCreatedAt));
                                                break;
                                        case "Log Level":
                                                logActivities.sort(Comparator.comparing(LogActivity::getLogLevel)
                                                                .thenComparing(LogActivity::getCreatedAt));
                                                break;
                                        default:
                                                // No sorting applied
                                                break;
                                }
                        }

                        // Update userMap
                        Response<ArrayList<User>> userResponse = userRepository.findAll(currentUser.getId());
                        if (userResponse.isSuccess()) {
                                for (User user : userResponse.getData()) {
                                        userMap.put(user.getId(), user.getUsername());
                                }
                        } else {
                                showError("Gagal memuat pengguna: " + userResponse.getMessage());
                        }

                        return logActivities;
                } catch (Exception e) {
                        // handle exception and return empty list
                        return Collections.emptyList();
                }
        }

        private void populateTableProducts(List<Product> products) {
                String[] columnNames = { "ID", "Nama", "Kategori", "Harga Beli", "Harga Jual", "Stok" };
                DefaultTableModel model = new DefaultTableModel(columnNames, 0);

                for (Product product : products) {
                        Object[] row = {
                                        product.getId(),
                                        product.getName(),
                                        categoryMap.getOrDefault(product.getCategoryId(), "Tidak Ditemukan"),
                                        product.getPurchasePrice(),
                                        product.getSellingPrice(),
                                        product.getStock()
                        };
                        model.addRow(row);
                }

                TabelManajemenBarang.setModel(model);
                TabelManajemenBarang.getSelectionModel().addListSelectionListener(e -> {
                        if (!e.getValueIsAdjusting()) {
                                selectedProduct();
                        }
                });

                int[] widths = { 50, 150, 100, 100, 100, 50 };
                for (int i = 0; i < widths.length; i++) {
                        TabelManajemenBarang.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
                }
        }

        private void populateTableRiwayatAktivitas(List<LogActivity> logActivities) {
                String[] columnNames = { "Tanggal", "Waktu", "Aktivitas", "User", "Log Level" };
                DefaultTableModel model = new DefaultTableModel(columnNames, 0);

                for (LogActivity logActivity : logActivities) {
                        Object[] row = {
                                        logActivity.getCreatedAt().toInstant().atZone(java.time.ZoneId.systemDefault())
                                                        .toLocalDate(),
                                        logActivity.getCreatedAt().toInstant().atZone(java.time.ZoneId.systemDefault())
                                                        .toLocalTime(),
                                        logActivity.getAction(),
                                        logActivity.getUserId(),
                                        logActivity.getLogLevel()
                        };
                        model.addRow(row);
                }

                TabelRiwayatAktivitas.setModel(model);
        }

        private void selectedProduct() {
                int selectedRow = TabelManajemenBarang.getSelectedRow();
                if (selectedRow != -1) {
                        IDBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 0).toString());
                        NamaBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 1).toString());
                        KategoriBarang.setSelectedItem(TabelManajemenBarang.getValueAt(selectedRow, 2).toString());
                        HargaBeliBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 3).toString());
                        HargaJualBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 4).toString());
                        StockBarang.setText(TabelManajemenBarang.getValueAt(selectedRow, 5).toString());
                }
        }

        private void showError(String message) {
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }

        private void clearForm() {
                IDBarang.setText("");
                NamaBarang.setText("");
                // BarcodeBarang.setText("");
                KategoriBarang.setSelectedIndex(-1);
                HargaBeliBarang.setText("");
                HargaJualBarang.setText("");
                StockBarang.setText("");
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ButtonEditBarang;
        private javax.swing.JButton ButtonHapusBarang;
        private javax.swing.JButton ButtonScanBarang;
        private javax.swing.JButton ButtonTambahBarang;
        private javax.swing.JTextField HargaBeliBarang;
        private javax.swing.JTextField HargaJualBarang;
        private javax.swing.JTextField IDBarang;
        private javax.swing.JComboBox<String> KategoriBarang;
        private javax.swing.JTextField NamaBarang;
        private javax.swing.JTextField SearchBarang;
        private javax.swing.JComboBox<String> SortItem;
        private javax.swing.JComboBox<String> SortRiwayatAktivitas;
        private javax.swing.JTextField StockBarang;
        private javax.swing.JTable TabelManajemenBarang;
        private javax.swing.JTable TabelRiwayatAktivitas;
        private javax.swing.JButton clearForm;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        // End of variables declaration//GEN-END:variables
}
